name: Generate and deploy

on: [push]

env:
  FOODDATA_ZIP_URL: 'https://fdc.nal.usda.gov/fdc-datasets/FoodData_Central_survey_food_json_2021-10-28.zip'
  FOODDATA_ZIP_FILENAME: 'FoodData_Central_survey_food_json_2021-10-28.zip'
  FOODDATA_JSON_FILENAME: 'FoodData_Central_survey_food_json_2021-10-28.json'
  FOODDATA_DIR: fooddata

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Load USDA FDC FoodData from cache
        id: download
        uses: actions/cache@v3
        with:
          path: ${{ env.FOODDATA_DIR }}
          key: ${{ env.FOODDATA_ZIP_URL }}
      - name: Download USDA FDC FoodData
        if: steps.download.outputs.cache-hit != 'true'
        run: >
          (
            mkdir -p "$FOODDATA_DIR" &&
            cd "$FOODDATA_DIR" &&
            if [ ! -f "$FOODDATA_ZIP_FILENAME" ]; then
              curl "$FOODDATA_ZIP_URL" -o "$FOODDATA_ZIP_FILENAME" &&
              unzip "$FOODDATA_ZIP_FILENAME";
            fi
          )
      - name: Set up symlinks for input files
        run: ln -s "$FOODDATA_DIR/$FOODDATA_JSON_FILENAME"
      - name: Install dependencies
        run: pip install monotable
      - name: Generate VegAttributes JSON
        run: python generate.py
      - name: Write file name of generated JSON to env
        run: >
          echo
          "GENERATED_JSON_FILENAME=VegAttributes_for_$FOODDATA_JSON_FILENAME"
          >> $GITHUB_ENV
      - name: Upload generated JSON as GitHub artifact
        uses: actions/upload-artifact@v3
        with:
          name: VegAttributes JSON
          path: ${{ env.GENERATED_JSON_FILENAME }}
      - name: Publish generated JSON as GitHub release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.GENERATED_JSON_FILENAME }}
      - name: Generate GitHub Pages contents
        run: |
          PYTHONPATH="$PWD" python .gh-pages/generate-pages.py
          cp .gh-pages/index.md pages-export/
      - name: Check out GitHub Pages branch (gh-pages)
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          clean: false
      - name: Copy pages-export folder contents over repo root for GitHub Pages
        run: cp -r pages-export/* ./
      - name: Commit and push changes for GitHub Pages
        run: >
          git config user.name 'github-actions-wf' &&
          shopt -s globstar &&
          git add *.md category-lists/*.md &&
          git commit -m 'Update GH pages contents' &&
          git push
